name: cots_2211104019_muhammad_edgar_nadhif
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/onboarding-1.png
    - assets/img/onboarding-2.png
    - assets/img/onboarding-3.png
    - assets/img/gojeklogo.png
    - assets/img/bahasa.png
  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SF-Pro-Text-Light.otf
          weight: 300
        - asset: assets/fonts/SF-Pro-Text-Heavy.otf
          weight: 800
    - family: SFProTextItalic
      fonts:
        - asset: assets/fonts/SF-Pro-Text-RegularItalic.otf
          style: italic
        - asset: assets/fonts/SF-Pro-Text-SemiboldItalic.otf
          style: italic
        - asset: assets/fonts/SF-Pro-Text-BoldItalic.otf
          style: italic
        - asset: assets/fonts/SF-Pro-Text-MediumItalic.otf
          style: italic
        - asset: assets/fonts/SF-Pro-Text-LightItalic.otf
          style: italic
        - asset: assets/fonts/SF-Pro-Text-HeavyItalic.otf
          style: italic
